client_script 'ped_shop.lua'
client_script 'ped_bank.lua'
client_script 'ped_shopclothes.lua'
client_script 'ped_shopfleeca.lua'
client_script 'ped_wel_police.lua'
client_script 'ped_police.lua'
client_script 'ped_sadot.lua'
client_script 'tp_client.lua'
client_script 'storespnj_client.lua'
--client_script 'ped_secu.lua'

server_script 'storespnj_server.lua'
